version: '3'
services:
  carcontacts:
    image: car-contacts-prod:latest
    build: .
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: $(SECRET_KEY_BASE)
    ports:
      - "3000:3000"
